# Generated by Django 4.2.4 on 2025-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_message_file_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
