# Generated by Django 4.2.4 on 2025-03-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_roomfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_video_call_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
